// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustimizeEmpty: typeof import('./src/components/custimizeEmpty.vue')['default']
    CustimizeSlogn: typeof import('./src/components/custimizeSlogn.vue')['default']
    CustomizeButton: typeof import('./src/components/customizeButton.vue')['default']
    CustomizeProcess: typeof import('./src/components/customizeProcess.vue')['default']
    CustomizeSkeleton: typeof import('./src/components/customizeSkeleton.vue')['default']
    CustomizeTab: typeof import('./src/components/customizeTab.vue')['default']
    CustomizeWrapper: typeof import('./src/components/customizeWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanList: typeof import('vant/es')['List']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}

export {}
